title: "Siv3D リファレンス v0.6（執筆中）"
summary: "◆ 内容\nゲーム、メディアアート、ビジュアライザ、シミュレータなど、可視化やインタラクションに関わる C++ プログラムを、楽しく簡単なコードで記述できるモダンなフレームワーク「Siv3D」のリファレンスです。\n\n◆ 対応バージョン\nOpenSiv3D v0.6"
topics: ["cpp", "siv3d"] # トピック（5つまで）
published: true # falseだと下書き
price: 0
chapters:
  - introduction
  - requirements
  - setup
  - hello-siv3d
  - quick-example
  - tutorial-basic
  - tutorial-shape
  - tutorial-animation
  - community
  - build
  - troubleshooting-setup