title: "Siv3D リファレンス v0.6.0（執筆中）"
summary: "◆ 内容\n2D/3D ゲーム、メディアアート、ビジュアライザ、シミュレータなど、可視化やインタラクションに関わるプログラムを、驚くほど短い、楽しく簡単なコードで書けるモダンな C++ フレームワーク Siv3D のリファレンスです。\n\n◆ 対応バージョン\nOpenSiv3D v0.6.0\nhttps://github.com/Siv3D/OpenSiv3D"
topics: ["cpp", "siv3d", "game", "gamedev"] # トピック（5つまで）
published: true # falseだと下書き
price: 0
chapters:
  - introduction
  - requirements
  - setup
  - hello-siv3d
  - quick-example
  - tutorial-basic
  - tutorial-shape
  - tutorial-animation
  - tutorial-shape-2
  - tutorial-string
  - tutorial-data-structure
  - tutorial-2d-intersection
  - tutorial-texture
  - tutorial-video
  - tutorial-format
  - tutorial-gui
  - tutorial-random
  - tutorial-time
  - tutorial-font
  - tutorial-scene
  - tutorial-keyboard
  - tutorial-mouse
  - tutorial-utility
  - tutorial-audio
  - tutorial-asset
  - tutorial-renderstates2d
  - tutorial-effect
  - tutorial-filesystem
  - tutorial-textfile
  - tutorial-configfile
  - tutorial-binaryfile
  - tutorial-dialog
  - tutorial-dragdrop
  - tutorial-http
  - tutorial-resource
  - tutorial-scene-manager
  - tutorial-gamepad
  - tutorial-image
  - tutorial-rendertexture
  - tutorial-shader2d
 # - tutorial-3d
 # - tutorial-shader3d
  - tutorial-webcam
  - tutorial-microphone
  - tutorial-tcp
  - tutorial-release
  - tutorial-next
  - sample-game
  - sample-application
  - sample-visual
  - community
  - event
  - contribute
  - sponsor
  - productivity
  - mascot
  - build
  - course-network-visualization
  - course-game-launcher
  - course-quick-turorial
  - troubleshooting-setup
  - troubleshooting-run
  - api-z
