title: "Siv3D リファレンス v0.6（執筆中）"
summary: "◆ 内容\n音・画像・インタラクションを楽しく簡単にプログラムできる C++ ライブラリ「OpenSiv3D」のリファレンスを執筆中です。\n\n◆ 対応バージョン\nOpenSiv3D v0.6"
topics: ["cpp", "siv3d"] # トピック（5つまで）
published: true # falseだと下書き
price: 0
chapters:
  - introduction
  - requirements
  - setup
  - hello-siv3d
  - quick-example
  - tutorial-basic
  - tutorial-shape
  - tutorial-animation
  - community
  - build
  - troubleshooting-setup