title: "Siv3D リファレンス v0.6.0（執筆中）"
summary: "◆ 内容\nゲーム、メディアアート、ビジュアライザ、シミュレータなど、可視化やインタラクションに関わる C++ プログラムを、楽しく簡単なコードで記述できるモダンなフレームワーク「Siv3D」のリファレンスです。\n\n◆ 対応バージョン\nOpenSiv3D v0.6.0"
topics: ["cpp", "siv3d"] # トピック（5つまで）
published: true # falseだと下書き
price: 0
chapters:
  - introduction
  - requirements
  - setup
  - hello-siv3d
  - quick-example
  - tutorial-basic
  - tutorial-shape
  - tutorial-animation
  - tutorial-shape-2
  - tutorial-string
  - tutorial-data-structure
  - tutorial-2d-intersection
  - tutorial-texture
  - tutorial-video
  - tutorial-format
  - tutorial-random
 # - tutorial-time
 # - tutorial-font
 # - tutorial-gui
 # - tutorial-scene
 # - tutorial-keyboard
 # - tutorial-mouse
 # - tutorial-audio
 # - tutorial-asset
 # - tutorial-renderstates2d
 # - tutorial-effect
 # - tutorial-filesystem
 # - tutorial-textfile
 # - tutorial-configfile
 # - tutorial-binaryfile
 # - tutorial-clipboard
 # - tutorial-dialog
 # - tutorial-dragdrop
 # - tutorial-http
 # - tutorial-resource
 # - tutorial-gamepad
 # - tutorial-image
 # - tutorial-texture-2
 # - tutorial-shader2d
 # - tutorial-webcam
 # - tutorial-microphone
 # - tutorial-scene-manager
 # - tutorial-3d
 # - tutorial-shader3d
  - sample-game
  - sample-application
  - sample-visual
  - community
  - mascot
  - build
  - troubleshooting-setup
  - troubleshooting-run
  - course-quick-turorial
