title: "Siv3D Reference v0.6.2 [English]"
summary: "Siv3D is a modern C++ framework for visualization and interaction in 2D/3D games, media art, visualizers, simulators, etc.\n\n◆ Supported Version\nOpenSiv3D v0.6.2\nhttps://github.com/Siv3D/OpenSiv3D\n\n◆ 日本語\nhttps://zenn.dev/reputeless/books/siv3d-documentation\n\n◆ Contribute to the translation\nhttps://github.com/Reputeless/Zenn.Public/tree/main/books/siv3d-documentation-en"
topics: ["cpp", "siv3d", "game", "gamedev"] # トピック（5つまで）
published: true # falseだと下書き
price: 0
chapters:
  - introduction
 # - whats-new
  - requirements
  - setup
  - hello-siv3d
  - quick-example
  - tutorial-basic
  - tutorial-shape
  - tutorial-animation
  - tutorial-shape-2
  - tutorial-string
  - tutorial-data-structure
  - tutorial-2d-intersection
  - tutorial-texture
  - tutorial-video
  - tutorial-format
  - tutorial-gui
  - tutorial-random
  - tutorial-time
  - tutorial-font
  - tutorial-scene
  - tutorial-keyboard
  - tutorial-mouse
  - tutorial-utility
  - tutorial-audio
  - tutorial-asset
  - tutorial-renderstates2d
  - tutorial-effect
  - tutorial-filesystem
  - tutorial-textfile
  - tutorial-configfile
  - tutorial-binaryfile
  - tutorial-dialog
  - tutorial-dragdrop
  - tutorial-http
  - tutorial-resource
  - tutorial-scene-manager
  - tutorial-gamepad
  - tutorial-image
  - tutorial-rendertexture
  - tutorial-shader2d
  - tutorial-3d
  - tutorial-3d-2
  - tutorial-3d-intersection
  - tutorial-microphone-webcam
  - tutorial-tcp
  - tutorial-release
  - tutorial-next
  - sample-game
  - sample-application
  - sample-visual
  - sample-algorithm
  - sample-ui
  - sample-image
  - sample-2d-physics
  - sample-device
  - sample-links
  - community
  - event
  - contribute
  - sponsor
  - mascot
  - build
  - guideline
  - productivity
  - course-circles
  - course-tic-tac-toe
  - course-network-visualization
  - course-game-launcher
  - course-quick-turorial
  - troubleshooting-setup
  - troubleshooting-run
  - api-b
  - api-c
  - api-p
  - api-q
  - api-r
  - api-s
  - api-t
  - api-u
  - api-z
