title: "競技プログラミングのための 標準 C++"
summary: "◆ 内容\n競技プログラミングで使える C++ の主要な標準機能のサンプル付き解説です。C++ のバージョンは C++17 です。\n　競技プログラミング独特のハックやスタイル（<bits/stdc++.h> や巨大な配列、using namespace std 等）の使用を避けているため、一般的な C++ ソフトウェア開発でも使える、また C++ 標準ライブラリの機能 (std:: から始まる) を意識したコーディングの練習ができます。\n\n◆ 対象読者\n・競プロ上達のために C++ 標準ライブラリを一通り学びたい方\n・コンテストで参照できる C++ ドキュメントを探している方\n\n◆ 本書へのご意見・ご提案\nhttps://github.com/Reputeless/Zenn.Public/issues \n全編無料公開ですが、購入していただけると筆が進みます。\n\n◆ 著者の記事\n・競プロに便利な C++17 新機能まとめ (https://qiita.com/Reputeless/items/db7dda0096f3ae91d450)\n・ゲーム開発者のための C++11〜C++20 技術書典 10 Ver. (https://zenn.dev/tetsurom/books/cpp11-cpp20-for-game-developers)\n・USACO (USA Computing Olympiad) コンテスト参加ガイド (https://qiita.com/Reputeless/items/537b90150a56643750aa)\n・冒険で学ぶ はじめてのプログラミング (https://gihyo.jp/book/2018/978-4-7741-9918-4)\n・C++ の歩き方 | cppmap (https://cppmap.github.io/)"
topics: ["cpp", "競プロ"] # トピック（5つまで）
published: false # falseだと下書き
price: 800
chapters:
  - library-string
