title: "競技プログラミングのための 標準 C++"
summary: "◆ 内容\n競技プログラミングで使える C++ の主要な標準機能のサンプル付き解説です。C++ のバージョンは C++17 です。\n競技プログラミング独特のハックやスタイル（`<bits/stdc++.h>` や巨大な配列、 `using namespace std` 等）の使用を避けているため、一般的な C++ ソフトウェア開発でも使える、また C++ 標準ライブラリの機能 (`std::` から始まる) を意識したコーディングの練習ができます。\n本書へのご意見・ご提案を GitHub リポジトリの Issue で受け付けています。ある程度コンテンツが揃うまでは、全範囲を無料で公開します。"
topics: ["cpp", "競プロ"] # トピック（5つまで）
published: false # falseだと下書き
price: 800
chapters:
  - library-string
