title: "競技プログラミングのための 標準 C++"
summary: "◆ 内容\n競技プログラミングで使える C++ の主要な標準機能のサンプル付き解説です。C++ のバージョンは C++17 です。\n\n競技プログラミング独特のハックやスタイル（<bits/stdc++.h> や巨大な配列、using namespace std 等）の使用を避けているため、一般的な C++ ソフトウェア開発でも使える、また C++ 標準ライブラリの機能 (std:: から始まる) を意識したコーディングの練習ができます。\n\n◆ 対象読者\n・競技プログラミングの上達のために C++ 標準ライブラリ機能を一通り学びたい方\n・コンテストで参照できる C++ ドキュメントを探している方\n\n◆ 本書へのご意見・ご提案\nhttps://github.com/Reputeless/Zenn.Public/issues \n全編無料公開ですが、購入していただけると筆が進みます。"
topics: ["cpp", "競プロ"] # トピック（5つまで）
published: false # falseだと下書き
price: 800
chapters:
  - library-string
